#!/bin/bash

# By Nathan Collings. Just a small script to disable the touchpad
# if you are using a laptop. Works on my Acer Aspire 5560-7414
# using Ubuntu 12.04. Your mileage my vary. At the very least
# you may have to make sure it's getting the correct id on the
# tpID line for your hardware and OS.

# Made because Ubuntu doesn't have a "disable touchpad when
# mouse is plugged in" feature.

NO_ARGS=0
E_OPTERROR=85

if [ $# -eq "$NO_ARGS" ]
then
	echo -e "Usage:"
	echo "disableTouchpad -[d][e]"
	echo "Options:"
	echo "-d = disable"
	echo "-e = enable"
	exit $E_OPTERROR
fi

#Snag the id of the touchpad
tpID=`xinput | grep Touchpad | awk '{print $6}' | awk -F = '{print $2}'`

while getopts ":de" Option
do
	case $Option in
		d	) xinput set-prop $tpID "Device Enabled" 0; echo "Touchpad disabled.";;
		e	) xinput set-prop $tpID "Device Enabled" 1; echo "Touchpad enabled.";;
	esac
done
